version: '3.5'

services:

  webapp:
    image: lucamaro/opendcim-container:18.02-0
    build: .
    env_file: .env
    environment:
      OPENDCIM_DB_HOST: db
      OPENDCIM_DB_NAME: ${MYSQL_DATABASE}
      OPENDCIM_DB_USER: ${MYSQL_USER}
      OPENDCIM_DB_PASS: ${MYSQL_PASSWORD}
      OPENDCIM_DB_PORT: 3306
    volumes:
      - dcim_data:/data
#      - ./certs:/certs
    networks:
      - database_net
      - outside
    ports:
      - ${DCIM_HTTP_PORT}:80
      - ${DCIM_HTTPS_PORT}:443

networks:
  database_net:
    driver: bridge
    internal: true
  outside:
    driver: bridge

volumes:
  dcim_data:
    driver: local

